REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM moexmon;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM squealer;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM moexmon;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM squealer;
REVOKE ALL PRIVILEGES ON DATABASE godfather FROM moexmon;
REVOKE ALL PRIVILEGES ON DATABASE godfather FROM squealer;
DROP USER IF EXISTS moexmon;
DROP USER IF EXISTS squealer;
