services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - 'godfather:/var/lib/postgresql/data'
    env_file: godfather.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U godfather"]
      interval: 3s
      timeout: 3s
      retries: 5
  godfather:
    image: godfather-cmd:multistage
    ports:
      - '9443:9443'
    depends_on:
      postgres:
        condition: service_healthy
    env_file: godfather.env

volumes:
  godfather:

