services:
  nats:
    image: nats:latest
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    volumes:
      - 'godfather:/data'
      - './nats-server.conf:/etc/nats/nats-server.conf'
    command: ["-c", "/etc/nats/nats-server.conf"]
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      #interval: 10s
      #timeout: 5s
      #retries: 3
      #start_period: 5s
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - 'godfather:/var/lib/postgresql/data'
    env_file: godfather.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U godfather"]
      interval: 3s
      timeout: 3s
      retries: 5
  godfather:
    image: godfather:latest
    ports:
      - '9443:9443'
    depends_on:
      postgres:
        condition: service_healthy
    env_file: godfather.env
  moexmon:
    image: moexmon:latest
    ports:
      - '9191:9191'
    depends_on:
      postgres:
        condition: service_healthy
      #nats:
      #  condition: service_healthy
    env_file: godfather.env

  squealer:
    image: squealer:latest
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    ports:
      - '9192:9192'

volumes:
  godfather:

